// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9FPT0Hoxp9LoG1hR0XA8Oby_j7Jh0bTY',
    appId: '1:221390324709:web:fc97b7c2099589dacce50c',
    messagingSenderId: '221390324709',
    projectId: 'fitflex-clau',
    authDomain: 'fitflex-clau.firebaseapp.com',
    storageBucket: 'fitflex-clau.firebasestorage.app',
    measurementId: 'G-NDZDVDHZ3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXtBDt1YmahUIsYmZM1n3GVwliPKmQds',
    appId: '1:221390324709:android:cb74a33b67685a46cce50c',
    messagingSenderId: '221390324709',
    projectId: 'fitflex-clau',
    storageBucket: 'fitflex-clau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8amoFWr3f_5uV5f_0TyxK6iSLxatI7Lk',
    appId: '1:221390324709:ios:b7d6c2c84b617178cce50c',
    messagingSenderId: '221390324709',
    projectId: 'fitflex-clau',
    storageBucket: 'fitflex-clau.firebasestorage.app',
    iosBundleId: 'com.example.fitflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8amoFWr3f_5uV5f_0TyxK6iSLxatI7Lk',
    appId: '1:221390324709:ios:b7d6c2c84b617178cce50c',
    messagingSenderId: '221390324709',
    projectId: 'fitflex-clau',
    storageBucket: 'fitflex-clau.firebasestorage.app',
    iosBundleId: 'com.example.fitflex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9FPT0Hoxp9LoG1hR0XA8Oby_j7Jh0bTY',
    appId: '1:221390324709:web:0f8181002cf323b7cce50c',
    messagingSenderId: '221390324709',
    projectId: 'fitflex-clau',
    authDomain: 'fitflex-clau.firebaseapp.com',
    storageBucket: 'fitflex-clau.firebasestorage.app',
    measurementId: 'G-RMYZBDM8XD',
  );
}
